typography_spectrum: 0.7587062062229961
color:
  brandColors:
    - '#ffffff'
    - '#cac5c1'
    - '#310605'
    - '#424242'
    - '#8f8777'
  brandStrength: 0.5401048548519611
  lightness: 0.21348658902570605
  saturation: 0.296082247979939
  rhythmicContrast: 0.4089528440963477
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8142538792453706
analytics:
  google: null
  facebook: null
  twitter: null
name: Test Altelis
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: essai
    id: 3bb14369-2474-4ea7-b279-df748df3b5be
    type: content
favicon: null
title: Altelis
description: Digital Marketing for Hotels
purpose: []
