layout_spectrum: 0.12436698563396931
typography_spectrum: 0.38915956881828606
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.31671235035173595
  lightness: 0.414071534993127
  saturation: 0.6340029754210263
  rhythmicContrast: 0.18233705474995077
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Test Altelis
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: essai
    id: 3bb14369-2474-4ea7-b279-df748df3b5be
    type: content
favicon: null
title: Altelis
description: Digital Marketing for Hotels
purpose: []
