name: Test Altelis
favicon: null
layout_spectrum: 0.8142538792453706
typography_spectrum: 0.7587062062229961
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5401048548519611
  lightness: 0.21348658902570605
  saturation: 0.296082247979939
  rhythmicContrast: 0.4089528440963477
purpose: []
